ETrade.UI/Models/ErrorViewModel.cs
namespace ETrade.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ETrade.UI/Models/ViewModel/BasketDetailModel.cs
using ETrade.Dto;
using ETrade.Entity.Concrete;

namespace ETrade.UI.Models.ViewModel
{
    public class BasketDetailModel
    {
        public List<ProductDTO> ProductDTOs { get; set; }
        public List<BasketDetailDTO> BasketDetailDTOs { get; set; }
        public decimal UnitPrice { get; set; }
        public int ProductId { get; set; }
        //Amount - Adet
        public int Amount { get; set; }
        //Ratio - Kdv oranı
        public decimal Ratio { get; set; }
        public int UnitId { get; set; }
    }
}

ETrade.UI/Models/ViewModel/UserModel.cs
using ETrade.Entity.Concrete;

namespace ETrade.UI.Models.ViewModel
{
    public class UserModel
    {
        public User User { get; set; }
        public List<County> Counties { get; set; }
        public string Msg { get; set; }
    }
}

ETrade.UI/Controllers/AdminController.cs
using ETrade.Dto;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace ETrade.UI.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            var usr = JsonConvert.DeserializeObject<UserDTO>(HttpContext.Session.GetString("User"));
            ViewBag.User = usr.Mail;
            return View();
        }
    }
}

ETrade.UI/Controllers/AuthController.cs
using ETrade.Dto;
using ETrade.Entity.Concrete;
using ETrade.Repos.Concretes;
using ETrade.UI.Models.ViewModel;
using ETrade.Uow;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace ETrade.UI.Controllers
{
    public class AuthController : Controller
    {
        public const string SessionUser = "";

        IUow _uow;
        UserModel _model;
        public AuthController(IUow uow, UserModel model)
        {
            _uow = uow;
            _model = model;
        }

        public IActionResult Register()
        {
            _model.User = new User();
            _model.Counties = _uow._CountyRep.List();
            return View(_model);
        }

        [HttpPost]
        public IActionResult Register(UserModel model)
        {
            model.User = _uow._UserRep.CreateUser(model.User);
            if (!model.User.Error)
            {
                //Burada şifreleme işlemi yaptık.
                _uow._UserRep.Add(model.User);
                _uow.Commit();
                return RedirectToAction("Index", "Home");
            }
            else
            {
                model.Msg = $"{model.User.Mail} zaten mevcut";
                model.Counties = _uow._CountyRep.List(); 
                return View(model);
            }
        }
        //Login olur olmaz hangi bilgilerle login olduğumuzu saklayacağız.
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(string Mail, string Password)
        {
            //Session
            UserDTO user = _uow._UserRep.Login(Mail, Password);

            if (user.Error == false) 
            {
                HttpContext.Session.SetString("User", JsonConvert.SerializeObject(user));
                if (user.Role == "Admin")
                {
                    return RedirectToAction("Index", "Admin");
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            return View();
        }
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

ETrade.UI/Controllers/BasketDetailController.cs
using ETrade.Dto;
using ETrade.Entity.Concrete;
using ETrade.UI.Models.ViewModel;
using ETrade.Uow;
using Microsoft.AspNetCore.Mvc;

namespace ETrade.UI.Controllers
{
    public class BasketDetailController : Controller
    {
        BasketDetailModel _detailModel;
        BasketDetail _basketDetail;
        IUow _uow;
        public BasketDetailController(BasketDetailModel detailModel, IUow uow, BasketDetail basketDetail)
        {
            _detailModel = detailModel;
            _basketDetail = basketDetail;
            _uow = uow;
        }

        public IActionResult Add(int id)
        {
            _detailModel.ProductDTOs = _uow._ProductRep.GetProductsSelect();
            _detailModel.BasketDetailDTOs = _uow._BasketDetailRep.BasketDetailDTOs(id);
            return View(_detailModel);
        }
        [HttpPost]
        public IActionResult Add(BasketDetailModel m, int id)
        {
            Product product = _uow._ProductRep.FindWithVat(m.ProductId);
            _basketDetail.Amount = m.Amount;
            _basketDetail.ProductId = m.ProductId;
            _basketDetail.Id = id;
            _basketDetail.OrderId = id;
            _basketDetail.UnitId = product.UnitId;
            //Araştır - Eager Loading lle metot girmek lazım.
            _basketDetail.Ratio = product.Vats.Ratio;
            _basketDetail.UnitPrice = product.UnitPrice;
            _uow._BasketDetailRep.Add(_basketDetail);
            _uow.Commit();

            return RedirectToAction("Add", new { id });
        }

        public IActionResult Delete(int id, int productId)
        {
            _uow._BasketDetailRep.Delete(id, productId);
            _uow.Commit();
            //IActionResult Add(int id) Add actionında int parametre göndermemiz gerekir.
            return RedirectToAction("Add", new { id });
        }

        public IActionResult Update(int id, int productId)
        {
            return View(_uow._BasketDetailRep.Find(id, productId));
        }

        [HttpPost]
        public IActionResult Update(int Amount, int id, int productId)
        {
            var selectedBasDetail = _uow._BasketDetailRep.Find(id, productId);
            selectedBasDetail.Amount = Amount;
            _uow._BasketDetailRep.Update(selectedBasDetail);
            _uow.Commit();
            return RedirectToAction("Add", new { id });
        }
    }
}

ETrade.UI/Controllers/BasketMasterController.cs
using ETrade.Dto;
using ETrade.Entity.Concrete;
using ETrade.Uow;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace ETrade.UI.Controllers
{
    public class BasketMasterController : Controller
    {
        IUow _uow;
        BasketMaster _basketMaster;
        public BasketMasterController(IUow uow, BasketMaster basketMaster)
        {
            _uow = uow;
            _basketMaster = basketMaster;
        }
        //Müşteri sepete ilk ürününü eklediğinde basket master oluşturulur ve oluşan master id yi basketmastera göndeririz.
        //İkinci bir ürün eklediğinde yeni sepet oluşturmamak için sipariş tamamlanmış mı tamamlanmamış mı diye completed ile kontrolünü sağlarız.
        //Yeni sipariş-ilk master kayıt- o id yi detayda kullanacak- sonra ürün girecek.
        //Ürün yoksa yeni bir basket master oluşturup id yi detay mastera göndeririz.
        public IActionResult Create()
        {
            var usr = JsonConvert.DeserializeObject<UserDTO>(HttpContext.Session.GetString("User"));
            var selectedBasket = _uow._BasketMasterRep.Set().FirstOrDefault(x => x.Completed == false && x.EntityId == usr.Id);
            if (selectedBasket != null)
            {
                return RedirectToAction("Add", "BasketDetail", new { id = selectedBasket.Id });
            }
            else
            {
                _basketMaster.OrderDate = DateTime.Now;
                _basketMaster.EntityId = usr.Id;
                _uow._BasketMasterRep.Add(_basketMaster);
                _uow.Commit();
                return RedirectToAction("Add", "BasketDetail", new { id = _basketMaster.Id });
            }
            return View();
        }
    }
}

ETrade.UI/Controllers/HomeController.cs
using ETrade.UI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ETrade.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ETrade.UI/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Hoşgeldiniz @ViewBag.User</h1>

ETrade.UI/Views/BasketDetail/Add.cshtml
@model ETrade.UI.Models.ViewModel.BasketDetailModel

<div class="row">
    <div class="col-md-7">
        <form method="post">
            <div>
                <label>Ürün</label>
                <select name="ProductId" class="form-control">
                    @foreach (var item in Model.ProductDTOs)
                    {
                        <option value="@item.Id">@item.ProductName</option>
                    }
                </select>
            </div>
            <div>
                <label>Miktar</label>
                <input class="form-control" type="Text" asp-for="Amount" />
            </div>
            <input type="submit" value="Ekle" />
            <a class="btn btn-primary" href="/Payment/Index">Siparişi Tamamla</a>
        </form>
        <table class="table table-hover">
            <tr>
                <th>Ürün Adı</th>
                <th>Miktar</th>
                <th>Birim</th>
                <th>KDV</th>
                <th>Birim Fiyatı</th>
                <th>Toplam Fiyat</th>
            </tr>
            @foreach (var item in Model.BasketDetailDTOs)
            {
                <tr>
                    <td>@item.ProductName</td>
                    <td>@item.Amount</td>
                    <td>@item.UnitName</td>
                    <td>@item.Ratio</td>
                    <td>@item.UnitPrice</td>
                    <td>@item.Total</td>
                    @*?productId = @item.ProductId    eşittirlerin yanına boşluk eklediğimiz zaman kod düzgün çalışmıyor ProductIdyi 0 alıyor.
                Htmlde debug yerine ekrana yazdırarak kontrolünü sağlamak daha sağlıklı.
                *@
                    <td><a class="btn btn-primary" href="/BasketDetail/Update/@item.Id/?productId=@item.ProductId">Değiştir</a></td>
                    <td><a class="btn btn-danger" href="/BasketDetail/Delete/@item.Id/?productId=@item.ProductId">Sil</a></td>
                </tr>
            }
        </table>
    </div>
    <div>
        <h4>Toplam : @Model.BasketDetailDTOs.Count() Adet Ürün @Model.BasketDetailDTOs.Sum(x=>x.Total)</h4>
    </div>
</div>

ETrade.UI/Views/BasketDetail/Update.cshtml
@model ETrade.Entity.Concrete.BasketDetail

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>BasketDetail</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ETrade.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ETrade.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ETrade.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ETrade.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ETrade.UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Lagout</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BasketMaster" asp-action="Create">AddtoBasket</a>
                        </li>
                        <li class="nav-item">
                            <p>@ViewBag.Name</p>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ETrade.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ETrade.UI/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ETrade.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ETrade.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-secondary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Admin</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Lagout</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BasketDetail" asp-action="Add">AddtoBasket</a>
                        </li>
                        <li class="nav-item">
                            <p>@ViewBag.Name</p>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ETrade.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>